sudo: required
dist: trusty
language: cpp
notifications:
  email: false
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-7
            - g++-7
            - cmake
      env: COMPILER=g++-7
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-trusty-4.0
            - llvm-toolchain-trusty
            - ubuntu-toolchain-r-test
          packages:
            - clang-4.0
            - cmake
      env: COMPILER=clang++-4.0
before_script:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev libboost-dev libboost-filesystem-dev
script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_CXX_COMPILER=$COMPILER .. && make
  
