sudo: required
dist: trusty
language: cpp
compiler:
  - clang
  - gcc
notifications:
  email: false
before_script:
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
  