sudo: required
dist: precise
language: cpp
notifications:
  email: false
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - gcc-6
            - g++-6
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          sources:
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise
            - ubuntu-toolchain-r-test
          packages:
            - clang-3.8
      env: COMPILER=clang++-3.8
before_script:
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get -qq update
  - sudo apt-get install -y libsdl2-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
  