sudo: required
dist: precise
language: cpp
notifications:
  email: false
matrix:
  include:
    - compiler: gcc
      addons:
        apt:
          packages:
            - g++-6
			- libsdl2-dev
      env: COMPILER=g++-6
    - compiler: clang
      addons:
        apt:
          packages:
            - clang-3.8
			- libsdl2-dev
      env: COMPILER=clang++-3.8
#before_script:
#  - sudo apt-get -qq update
#  - sudo apt-get install -y libsdl2-dev
script:
  - mkdir build
  - cd build
  - cmake .. && make
  